---
title: "Examples for Sub Zero Presentation"
author: "Phil Henrickson"
date: "`r Sys.Date()`"
output: 
  html_document:
        toc: true
        toc_depth: 2
        number_sections: true
---

```{r global settings, echo=F, warning=F, message=F, results = 'hide'}

knitr::opts_chunk$set(echo = F,
                      error=F,
                      dev="png",
                      fig.width = 10,
                      fig.height = 6)

options(knitr.duplicate.label = "allow")
options(scipen=999)

library(tidyverse)
library(tsibble)
library(fable)
library(ggthemes)
library(feasts)
library(fpp3)
library(lubridate)
library(viridis)
library(ggforce)
library(flextable)

# create custom theme

theme_phil <- function () { 
        
        theme_minimal() %+replace%
                theme(
                        axis.title = element_text(),
                       # strip.background = element_rect(fill="grey100"),
                        #strip.text = element_text(colour = 'black'),
                      #  strip.text.x = element_text(size = 7),
                      #  strip.text.y = element_text(size = 7),
                        legend.position = "top",
                      plot.subtitle = element_text(size = 10,
                                                   hjust = 0),
                      axis.text.x = element_text(size=rel(0.75),
                                                 vjust = 1),
                      axis.text.y = element_text(size=rel(0.75),
                                                 hjust = 1),
                      plot.caption = element_text(size=8,
                                                  hjust = 1,
                                                  vjust = 1,
                                                  margin = unit(c(6,0,0,0), "points")),
                        legend.title = element_blank(),
                        panel.grid.minor = element_blank(),
                       panel.spacing = unit(6.5, "mm"),
                #      strip.text.y = element_text(family = "sans", colour = "#3C3C3C", size = 8),
                 #     strip.text.x = element_text(family = "sans", colour = "#3C3C3C", size = 8),
                  #    strip.background = element_rect(fill="grey80"),
                      panel.grid = element_line(colour = "grey90")
                      
                      # remove spacing between facets
                      
                )
                
}


```

# Forecasting

## Simple Forecasting Models

```{r demosntrate prophet model}

library(fable.prophet)

cement <- aus_production %>%
        filter(year(Quarter) >= 1988)
train <- cement %>%
        filter(year(Quarter) <= 2007)

# plot the time series
train %>%
autoplot(Beer)+
        theme_bw()

# ts_display
train %>%
        gg_tsdisplay(Beer)

# fit an arima, ETS, and prophet model
fit <- train %>%
  model(
          naive = NAIVE(Cement),
          snaive = SNAIVE(Cement),
          arima = ARIMA(Cement),
          TSLM = TSLM(Cement ~ trend() + season()),
          ets = ETS(Cement),
          prophet = prophet(Cement ~ season(period = 4, order = 2,
                                    type = "multiplicative"))
  )

```


```{r show forecast, warning=F, message=F}

# =show forecast
fc <- fit %>% 
        forecast(h = "3 years")

# # forecasted
# fc %>%
#         autoplot(train)+
#         theme_bw()+
#         facet_wrap(.model ~.)

# overlay actual
fc %>%
        autoplot(cement)+
        theme_bw()+
        facet_wrap(.model ~.)+
        scale_x_yearquarter(date_breaks = "8 year",
                            minor_breaks = "1 year")

# check accuracy
fc %>%
        accuracy(cement) %>%
        mutate_if(is.numeric, round, 2) %>%
        arrange(MAPE) %>%
        flextable() %>%
        autofit()

```

Plot residuals of models

```{r check residuals of simple models}

# residuals of models
fit %>%
        select(arima) %>%
        gg_tsresiduals()+
        labs(title = "ARIMA")

fit %>%
        select(TSLM) %>%
        gg_tsresiduals()+
        labs(title = "TSLM")

fit %>%
        select(prophet) %>%
        gg_tsresiduals()+
        labs(title = "prophet")

```


## Complex Seasonality

Example of a noisy time series.

```{r show calls data, warning=F, message=F}


calls  = bank_calls %>%
        as_tsibble() %>%
        tsibble::fill_gaps() %>%
        mutate(day = wday(DateTime, label=T))

# plot time series
calls %>%
        autoplot(Calls)+
        theme_bw(16)
        # geom_smooth(method = 'loess',
        #             formula = 'y ~ x')
```

Zoom in to first month.

```{r zoom in to period}

# zoom
calls_dat %>%
        as_tibble() %>%
        ggplot(., 
               aes(x=DateTime,
               y = Calls))+
        geom_line()+
        facet_zoom(xlim = c(as_datetime(as.Date(min(bank_calls$DateTime))),
                            as_datetime(as.Date(min(bank_calls$DateTime))+28)))+
        theme_bw(16)


```

Show the daily call pattern

```{r plot by time and day of week, warning=F, messaage=F}

library(anytime)

calls_dat %>%
        gg_season(Calls,
                  color = 'grey60',
                  alpha = 0.6,
                  period = "day")+
        theme_bw()

calls_dat %>%
        gg_season(Calls,
                  color = 'grey60',
                  alpha = 0.6,
                  period = "week")+
        theme_bw()

```

Decompose

```{r decomposition}

calls <- bank_calls %>%
  mutate(t = row_number()) %>%
  update_tsibble(index = t, regular = TRUE)


# decompose
calls %>%
  model(
    STL(sqrt(Calls) ~ season(period = 169) +
                      season(period = 5*169),
        robust = TRUE)
  ) %>%
  components() %>%
  autoplot() + 
        labs(x = "Observation")+
        theme_bw()

```


```{r forecast}

my_dcmp_spec <- decomposition_model(
  STL(sqrt(Calls) ~ season(period = 169) +
                    season(period = 5*169),
      robust = TRUE),
  ETS(season_adjust ~ season("N"))
)
fc <- calls %>%
  model(my_dcmp_spec) %>%
  forecast(h = 5 * 169)

# Add correct time stamps to fable
fc_with_times <- bank_calls %>%
  new_data(n = 7 * 24 * 60 / 5) %>%
  mutate(time = format(DateTime, format = "%H:%M:%S")) %>%
  filter(
    time %in% format(bank_calls$DateTime, format = "%H:%M:%S"),
    wday(DateTime, week_start = 1) <= 5
  ) %>%
  mutate(t = row_number() + max(calls$t)) %>%
  left_join(fc, by = "t") %>%
  as_fable(response = "Calls", distribution = Calls)

# plot results
fc_with_times %>%
        fill_gaps() %>%
        autoplot(bank_calls %>% fill_gaps())+
        labs(y = "Calls",
             title = "Five-minute call volume to bank")+
        theme_bw()

# Plot results with last 3 weeks of data
fc_with_times %>%
  fill_gaps() %>%
  autoplot(bank_calls %>% tail(14 * 169) %>% fill_gaps()) +
  labs(y = "Calls",
       title = "Five-minute call volume to bank")+
        theme_bw()

```

## Hierarchical Models
Example of a grouped time series.

```{r get data, fig.height=8, fig.width=10}

tourism <- tsibble::tourism %>%
  mutate(State = recode(State,
    `New South Wales` = "NSW",
    `Northern Territory` = "NT",
    `Queensland` = "QLD",
    `South Australia` = "SA",
    `Tasmania` = "TAS",
    `Victoria` = "VIC",
    `Western Australia` = "WA"
))

# overall
tourism %>%
        group_by(Purpose) %>%
        summarize(Trips = sum(Trips)) %>%
        ggplot(., aes(x=Quarter,
                      y = Trips,
                      color = Purpose))+
        geom_line()+
        theme_minimal()+
        scale_color_colorblind()

# overall
tourism %>%
        group_by(Purpose) %>%
        summarize(Trips = sum(Trips)) %>%
        ggplot(., aes(x=Quarter,
                      y = Trips,
                      color = Purpose))+
        geom_line()+
        theme_minimal()+
        scale_color_colorblind()

# types 
tourism %>%
        filter(State == 'QLD') %>%
        ggplot(., aes(x=Quarter,
                      y = Trips,
                      color = Purpose))+
        geom_line()+
        facet_wrap(State ~ Region)+
        theme_minimal()+
        scale_color_colorblind()

# make hts
tourism_hts <- tourism %>%
  aggregate_key(State / Region, Trips = sum(Trips))

# plot hierarchical
 tourism_hts %>%
  filter(is_aggregated(Region)) %>%
         autoplot(Trips,
                  color = 'black')+
         theme_phil()+
           labs(y = "Trips ('000)",
                title = "Australian tourism: national and states") +
         facet_wrap(vars(State),
                    scales = "free_y",
                    ncol = 3)+
         theme(legend.position = "none")
 
```

```{r plot seasonally, fig.width=10}

# plot hierarchical
tourism %>%
        group_by(State) %>%
        summarise(Trips = sum(Trips)) %>%
        gg_season(Trips) +
        theme_phil()
        
        

gg_season(holidays, Trips) +
  labs(y = "Overnight trips ('000)",
       title = "Australian domestic holidays")+
        theme_minimal()+
        scale_color_binned()


        ?Scale_colgroup_by(Region) %>%
        summarize(trips = summarize(Trips)) %>%
        gg_season(trips, Region) +
        theme_phil()+
           labs(y = "Trips in Thousands",
                title = "Australian tourism: national and states")
         facet_wrap(vars(State),
                    scales = "free_y")+
         theme(legend.position = "none")



```



# Classification